/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.AIEvaluation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AIEvaluation', function() {
    it('should create an instance of AIEvaluation', function() {
      // uncomment below and update the code to test AIEvaluation
      //var instance = new UgcGuardJavascriptApi.AIEvaluation();
      //expect(instance).to.be.a(UgcGuardJavascriptApi.AIEvaluation);
    });

    it('should have the property aiSelectedCategory (base name: "ai_selected_category")', function() {
      // uncomment below and update the code to test the property aiSelectedCategory
      //var instance = new UgcGuardJavascriptApi.AIEvaluation();
      //expect(instance).to.be();
    });

    it('should have the property severity (base name: "severity")', function() {
      // uncomment below and update the code to test the property severity
      //var instance = new UgcGuardJavascriptApi.AIEvaluation();
      //expect(instance).to.be();
    });

    it('should have the property explanation (base name: "explanation")', function() {
      // uncomment below and update the code to test the property explanation
      //var instance = new UgcGuardJavascriptApi.AIEvaluation();
      //expect(instance).to.be();
    });

    it('should have the property actionRecommendation (base name: "action_recommendation")', function() {
      // uncomment below and update the code to test the property actionRecommendation
      //var instance = new UgcGuardJavascriptApi.AIEvaluation();
      //expect(instance).to.be();
    });

    it('should have the property reportId (base name: "report_id")', function() {
      // uncomment below and update the code to test the property reportId
      //var instance = new UgcGuardJavascriptApi.AIEvaluation();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new UgcGuardJavascriptApi.AIEvaluation();
      //expect(instance).to.be();
    });

    it('should have the property aiModel (base name: "ai_model")', function() {
      // uncomment below and update the code to test the property aiModel
      //var instance = new UgcGuardJavascriptApi.AIEvaluation();
      //expect(instance).to.be();
    });

    it('should have the property generatedTokens (base name: "generated_tokens")', function() {
      // uncomment below and update the code to test the property generatedTokens
      //var instance = new UgcGuardJavascriptApi.AIEvaluation();
      //expect(instance).to.be();
    });

  });

}));
