/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.BodyCreateMagicReport();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BodyCreateMagicReport', function() {
    it('should create an instance of BodyCreateMagicReport', function() {
      // uncomment below and update the code to test BodyCreateMagicReport
      //var instance = new UgcGuardJavascriptApi.BodyCreateMagicReport();
      //expect(instance).to.be.a(UgcGuardJavascriptApi.BodyCreateMagicReport);
    });

    it('should have the property report (base name: "report")', function() {
      // uncomment below and update the code to test the property report
      //var instance = new UgcGuardJavascriptApi.BodyCreateMagicReport();
      //expect(instance).to.be();
    });

    it('should have the property reporter (base name: "reporter")', function() {
      // uncomment below and update the code to test the property reporter
      //var instance = new UgcGuardJavascriptApi.BodyCreateMagicReport();
      //expect(instance).to.be();
    });

    it('should have the property mainContent (base name: "main_content")', function() {
      // uncomment below and update the code to test the property mainContent
      //var instance = new UgcGuardJavascriptApi.BodyCreateMagicReport();
      //expect(instance).to.be();
    });

    it('should have the property mainContentSender (base name: "main_content_sender")', function() {
      // uncomment below and update the code to test the property mainContentSender
      //var instance = new UgcGuardJavascriptApi.BodyCreateMagicReport();
      //expect(instance).to.be();
    });

    it('should have the property reportContext (base name: "report_context")', function() {
      // uncomment below and update the code to test the property reportContext
      //var instance = new UgcGuardJavascriptApi.BodyCreateMagicReport();
      //expect(instance).to.be();
    });

    it('should have the property reportContextPersons (base name: "report_context_persons")', function() {
      // uncomment below and update the code to test the property reportContextPersons
      //var instance = new UgcGuardJavascriptApi.BodyCreateMagicReport();
      //expect(instance).to.be();
    });

    it('should have the property channels (base name: "channels")', function() {
      // uncomment below and update the code to test the property channels
      //var instance = new UgcGuardJavascriptApi.BodyCreateMagicReport();
      //expect(instance).to.be();
    });

  });

}));
