/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.Content();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Content', function() {
    it('should create an instance of Content', function() {
      // uncomment below and update the code to test Content
      //var instance = new UgcGuardJavascriptApi.Content();
      //expect(instance).to.be.a(UgcGuardJavascriptApi.Content);
    });

    it('should have the property bodyType (base name: "body_type")', function() {
      // uncomment below and update the code to test the property bodyType
      //var instance = new UgcGuardJavascriptApi.Content();
      //expect(instance).to.be();
    });

    it('should have the property body (base name: "body")', function() {
      // uncomment below and update the code to test the property body
      //var instance = new UgcGuardJavascriptApi.Content();
      //expect(instance).to.be();
    });

    it('should have the property mediaIdentifiers (base name: "media_identifiers")', function() {
      // uncomment below and update the code to test the property mediaIdentifiers
      //var instance = new UgcGuardJavascriptApi.Content();
      //expect(instance).to.be();
    });

    it('should have the property extraData (base name: "extra_data")', function() {
      // uncomment below and update the code to test the property extraData
      //var instance = new UgcGuardJavascriptApi.Content();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new UgcGuardJavascriptApi.Content();
      //expect(instance).to.be();
    });

    it('should have the property uniquePartnerId (base name: "unique_partner_id")', function() {
      // uncomment below and update the code to test the property uniquePartnerId
      //var instance = new UgcGuardJavascriptApi.Content();
      //expect(instance).to.be();
    });

    it('should have the property ip (base name: "ip")', function() {
      // uncomment below and update the code to test the property ip
      //var instance = new UgcGuardJavascriptApi.Content();
      //expect(instance).to.be();
    });

    it('should have the property creatorId (base name: "creator_id")', function() {
      // uncomment below and update the code to test the property creatorId
      //var instance = new UgcGuardJavascriptApi.Content();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new UgcGuardJavascriptApi.Content();
      //expect(instance).to.be();
    });

    it('should have the property reportId (base name: "report_id")', function() {
      // uncomment below and update the code to test the property reportId
      //var instance = new UgcGuardJavascriptApi.Content();
      //expect(instance).to.be();
    });

  });

}));
