/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.File();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('File', function() {
    it('should create an instance of File', function() {
      // uncomment below and update the code to test File
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be.a(UgcGuardJavascriptApi.File);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property reportId (base name: "report_id")', function() {
      // uncomment below and update the code to test the property reportId
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property contentId (base name: "content_id")', function() {
      // uncomment below and update the code to test the property contentId
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property filePath (base name: "file_path")', function() {
      // uncomment below and update the code to test the property filePath
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property fileType (base name: "file_type")', function() {
      // uncomment below and update the code to test the property fileType
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property fileSize (base name: "file_size")', function() {
      // uncomment below and update the code to test the property fileSize
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property blurHash (base name: "blur_hash")', function() {
      // uncomment below and update the code to test the property blurHash
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property uploaderId (base name: "uploader_id")', function() {
      // uncomment below and update the code to test the property uploaderId
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property inS3 (base name: "in_s3")', function() {
      // uncomment below and update the code to test the property inS3
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property secret (base name: "secret")', function() {
      // uncomment below and update the code to test the property secret
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property uploadedAt (base name: "uploaded_at")', function() {
      // uncomment below and update the code to test the property uploadedAt
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property removedAt (base name: "removed_at")', function() {
      // uncomment below and update the code to test the property removedAt
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

    it('should have the property moduleId (base name: "module_id")', function() {
      // uncomment below and update the code to test the property moduleId
      //var instance = new UgcGuardJavascriptApi.File();
      //expect(instance).to.be();
    });

  });

}));
