/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.ModuleStats();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModuleStats', function() {
    it('should create an instance of ModuleStats', function() {
      // uncomment below and update the code to test ModuleStats
      //var instance = new UgcGuardJavascriptApi.ModuleStats();
      //expect(instance).to.be.a(UgcGuardJavascriptApi.ModuleStats);
    });

    it('should have the property moduleId (base name: "module_id")', function() {
      // uncomment below and update the code to test the property moduleId
      //var instance = new UgcGuardJavascriptApi.ModuleStats();
      //expect(instance).to.be();
    });

    it('should have the property totalReports (base name: "total_reports")', function() {
      // uncomment below and update the code to test the property totalReports
      //var instance = new UgcGuardJavascriptApi.ModuleStats();
      //expect(instance).to.be();
    });

    it('should have the property totalFiles (base name: "total_files")', function() {
      // uncomment below and update the code to test the property totalFiles
      //var instance = new UgcGuardJavascriptApi.ModuleStats();
      //expect(instance).to.be();
    });

    it('should have the property totalReporters (base name: "total_reporters")', function() {
      // uncomment below and update the code to test the property totalReporters
      //var instance = new UgcGuardJavascriptApi.ModuleStats();
      //expect(instance).to.be();
    });

    it('should have the property totalActions (base name: "total_actions")', function() {
      // uncomment below and update the code to test the property totalActions
      //var instance = new UgcGuardJavascriptApi.ModuleStats();
      //expect(instance).to.be();
    });

    it('should have the property totalTypes (base name: "total_types")', function() {
      // uncomment below and update the code to test the property totalTypes
      //var instance = new UgcGuardJavascriptApi.ModuleStats();
      //expect(instance).to.be();
    });

    it('should have the property totalOpenReports (base name: "total_open_reports")', function() {
      // uncomment below and update the code to test the property totalOpenReports
      //var instance = new UgcGuardJavascriptApi.ModuleStats();
      //expect(instance).to.be();
    });

  });

}));
