/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.Report();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Report', function() {
    it('should create an instance of Report', function() {
      // uncomment below and update the code to test Report
      //var instance = new UgcGuardJavascriptApi.Report();
      //expect(instance).to.be.a(UgcGuardJavascriptApi.Report);
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new UgcGuardJavascriptApi.Report();
      //expect(instance).to.be();
    });

    it('should have the property moduleId (base name: "module_id")', function() {
      // uncomment below and update the code to test the property moduleId
      //var instance = new UgcGuardJavascriptApi.Report();
      //expect(instance).to.be();
    });

    it('should have the property typeId (base name: "type_id")', function() {
      // uncomment below and update the code to test the property typeId
      //var instance = new UgcGuardJavascriptApi.Report();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new UgcGuardJavascriptApi.Report();
      //expect(instance).to.be();
    });

    it('should have the property reportState (base name: "report_state")', function() {
      // uncomment below and update the code to test the property reportState
      //var instance = new UgcGuardJavascriptApi.Report();
      //expect(instance).to.be();
    });

    it('should have the property mainContentId (base name: "main_content_id")', function() {
      // uncomment below and update the code to test the property mainContentId
      //var instance = new UgcGuardJavascriptApi.Report();
      //expect(instance).to.be();
    });

    it('should have the property reportedAt (base name: "reported_at")', function() {
      // uncomment below and update the code to test the property reportedAt
      //var instance = new UgcGuardJavascriptApi.Report();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new UgcGuardJavascriptApi.Report();
      //expect(instance).to.be();
    });

    it('should have the property secret (base name: "secret")', function() {
      // uncomment below and update the code to test the property secret
      //var instance = new UgcGuardJavascriptApi.Report();
      //expect(instance).to.be();
    });

  });

}));
