/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.ReportersWithPerson();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReportersWithPerson', function() {
    it('should create an instance of ReportersWithPerson', function() {
      // uncomment below and update the code to test ReportersWithPerson
      //var instance = new UgcGuardJavascriptApi.ReportersWithPerson();
      //expect(instance).to.be.a(UgcGuardJavascriptApi.ReportersWithPerson);
    });

    it('should have the property reportId (base name: "report_id")', function() {
      // uncomment below and update the code to test the property reportId
      //var instance = new UgcGuardJavascriptApi.ReportersWithPerson();
      //expect(instance).to.be();
    });

    it('should have the property reporterId (base name: "reporter_id")', function() {
      // uncomment below and update the code to test the property reporterId
      //var instance = new UgcGuardJavascriptApi.ReportersWithPerson();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new UgcGuardJavascriptApi.ReportersWithPerson();
      //expect(instance).to.be();
    });

    it('should have the property reporterCategory (base name: "reporter_category")', function() {
      // uncomment below and update the code to test the property reporterCategory
      //var instance = new UgcGuardJavascriptApi.ReportersWithPerson();
      //expect(instance).to.be();
    });

    it('should have the property customMessage (base name: "custom_message")', function() {
      // uncomment below and update the code to test the property customMessage
      //var instance = new UgcGuardJavascriptApi.ReportersWithPerson();
      //expect(instance).to.be();
    });

    it('should have the property reporter (base name: "reporter")', function() {
      // uncomment below and update the code to test the property reporter
      //var instance = new UgcGuardJavascriptApi.ReportersWithPerson();
      //expect(instance).to.be();
    });

  });

}));
