/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AIEvaluation from './AIEvaluation';
import AiModel from './AiModel';

/**
 * The AIEnrichedAnswer model module.
 * @module model/AIEnrichedAnswer
 * @version 1.0.0
 */
class AIEnrichedAnswer {
    /**
     * Constructs a new <code>AIEnrichedAnswer</code>.
     * Represents an enriched answer with all evaluations for a report, and all enabled AI models.
     * @alias module:model/AIEnrichedAnswer
     */
    constructor() { 
        
        AIEnrichedAnswer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AIEnrichedAnswer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AIEnrichedAnswer} obj Optional instance to populate.
     * @return {module:model/AIEnrichedAnswer} The populated <code>AIEnrichedAnswer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AIEnrichedAnswer();

            if (data.hasOwnProperty('evaluations')) {
                obj['evaluations'] = ApiClient.convertToType(data['evaluations'], [AIEvaluation]);
            }
            if (data.hasOwnProperty('ai_models')) {
                obj['ai_models'] = ApiClient.convertToType(data['ai_models'], [AiModel]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AIEnrichedAnswer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AIEnrichedAnswer</code>.
     */
    static validateJSON(data) {
        if (data['evaluations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['evaluations'])) {
                throw new Error("Expected the field `evaluations` to be an array in the JSON data but got " + data['evaluations']);
            }
            // validate the optional field `evaluations` (array)
            for (const item of data['evaluations']) {
                AIEvaluation.validateJSON(item);
            };
        }
        if (data['ai_models']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ai_models'])) {
                throw new Error("Expected the field `ai_models` to be an array in the JSON data but got " + data['ai_models']);
            }
            // validate the optional field `ai_models` (array)
            for (const item of data['ai_models']) {
                AiModel.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/AIEvaluation>} evaluations
 */
AIEnrichedAnswer.prototype['evaluations'] = undefined;

/**
 * @member {Array.<module:model/AiModel>} ai_models
 */
AIEnrichedAnswer.prototype['ai_models'] = undefined;






export default AIEnrichedAnswer;

