/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AIUsage model module.
 * @module model/AIUsage
 * @version 1.0.0
 */
class AIUsage {
    /**
     * Constructs a new <code>AIUsage</code>.
     * Logs the usage of AI models per organization per month.
     * @alias module:model/AIUsage
     * @param organizationId {String} 
     * @param month {Number} The month of the AI
     * @param year {Number} The year of the AI usage
     * @param aiModel {String} 
     */
    constructor(organizationId, month, year, aiModel) { 
        
        AIUsage.initialize(this, organizationId, month, year, aiModel);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, organizationId, month, year, aiModel) { 
        obj['organization_id'] = organizationId;
        obj['month'] = month;
        obj['year'] = year;
        obj['ai_model'] = aiModel;
        obj['usage_count'] = 0;
    }

    /**
     * Constructs a <code>AIUsage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AIUsage} obj Optional instance to populate.
     * @return {module:model/AIUsage} The populated <code>AIUsage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AIUsage();

            if (data.hasOwnProperty('organization_id')) {
                obj['organization_id'] = ApiClient.convertToType(data['organization_id'], 'String');
            }
            if (data.hasOwnProperty('month')) {
                obj['month'] = ApiClient.convertToType(data['month'], 'Number');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('ai_model')) {
                obj['ai_model'] = ApiClient.convertToType(data['ai_model'], 'String');
            }
            if (data.hasOwnProperty('usage_count')) {
                obj['usage_count'] = ApiClient.convertToType(data['usage_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AIUsage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AIUsage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AIUsage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['organization_id'] && !(typeof data['organization_id'] === 'string' || data['organization_id'] instanceof String)) {
            throw new Error("Expected the field `organization_id` to be a primitive type in the JSON string but got " + data['organization_id']);
        }
        // ensure the json data is a string
        if (data['ai_model'] && !(typeof data['ai_model'] === 'string' || data['ai_model'] instanceof String)) {
            throw new Error("Expected the field `ai_model` to be a primitive type in the JSON string but got " + data['ai_model']);
        }

        return true;
    }


}

AIUsage.RequiredProperties = ["organization_id", "month", "year", "ai_model"];

/**
 * @member {String} organization_id
 */
AIUsage.prototype['organization_id'] = undefined;

/**
 * The month of the AI
 * @member {Number} month
 */
AIUsage.prototype['month'] = undefined;

/**
 * The year of the AI usage
 * @member {Number} year
 */
AIUsage.prototype['year'] = undefined;

/**
 * @member {String} ai_model
 */
AIUsage.prototype['ai_model'] = undefined;

/**
 * @member {Number} usage_count
 * @default 0
 */
AIUsage.prototype['usage_count'] = 0;






export default AIUsage;

