/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AnonymousPerson model module.
 * @module model/AnonymousPerson
 * @version 1.0.0
 */
class AnonymousPerson {
    /**
     * Constructs a new <code>AnonymousPerson</code>.
     * A person is a user that created the content.
     * @alias module:model/AnonymousPerson
     * @param moduleId {String} 
     */
    constructor(moduleId) { 
        
        AnonymousPerson.initialize(this, moduleId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, moduleId) { 
        obj['module_id'] = moduleId;
    }

    /**
     * Constructs a <code>AnonymousPerson</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnonymousPerson} obj Optional instance to populate.
     * @return {module:model/AnonymousPerson} The populated <code>AnonymousPerson</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnonymousPerson();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('module_id')) {
                obj['module_id'] = ApiClient.convertToType(data['module_id'], 'String');
            }
            if (data.hasOwnProperty('unique_partner_id')) {
                obj['unique_partner_id'] = ApiClient.convertToType(data['unique_partner_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnonymousPerson</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnonymousPerson</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AnonymousPerson.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['module_id'] && !(typeof data['module_id'] === 'string' || data['module_id'] instanceof String)) {
            throw new Error("Expected the field `module_id` to be a primitive type in the JSON string but got " + data['module_id']);
        }
        // ensure the json data is a string
        if (data['unique_partner_id'] && !(typeof data['unique_partner_id'] === 'string' || data['unique_partner_id'] instanceof String)) {
            throw new Error("Expected the field `unique_partner_id` to be a primitive type in the JSON string but got " + data['unique_partner_id']);
        }

        return true;
    }


}

AnonymousPerson.RequiredProperties = ["module_id"];

/**
 * @member {String} id
 */
AnonymousPerson.prototype['id'] = undefined;

/**
 * @member {String} module_id
 */
AnonymousPerson.prototype['module_id'] = undefined;

/**
 * @member {String} unique_partner_id
 */
AnonymousPerson.prototype['unique_partner_id'] = undefined;






export default AnonymousPerson;

