/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MailTemplate from './MailTemplate';
import MailTemplateBase from './MailTemplateBase';

/**
 * The MailTemplatesWithDefaults model module.
 * @module model/MailTemplatesWithDefaults
 * @version 1.0.0
 */
class MailTemplatesWithDefaults {
    /**
     * Constructs a new <code>MailTemplatesWithDefaults</code>.
     * A model that combines all mail templates for a module with default templates.
     * @alias module:model/MailTemplatesWithDefaults
     */
    constructor() { 
        
        MailTemplatesWithDefaults.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MailTemplatesWithDefaults</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MailTemplatesWithDefaults} obj Optional instance to populate.
     * @return {module:model/MailTemplatesWithDefaults} The populated <code>MailTemplatesWithDefaults</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MailTemplatesWithDefaults();

            if (data.hasOwnProperty('module_templates')) {
                obj['module_templates'] = ApiClient.convertToType(data['module_templates'], [MailTemplate]);
            }
            if (data.hasOwnProperty('default_templates')) {
                obj['default_templates'] = ApiClient.convertToType(data['default_templates'], [MailTemplateBase]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MailTemplatesWithDefaults</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MailTemplatesWithDefaults</code>.
     */
    static validateJSON(data) {
        if (data['module_templates']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['module_templates'])) {
                throw new Error("Expected the field `module_templates` to be an array in the JSON data but got " + data['module_templates']);
            }
            // validate the optional field `module_templates` (array)
            for (const item of data['module_templates']) {
                MailTemplate.validateJSON(item);
            };
        }
        if (data['default_templates']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['default_templates'])) {
                throw new Error("Expected the field `default_templates` to be an array in the JSON data but got " + data['default_templates']);
            }
            // validate the optional field `default_templates` (array)
            for (const item of data['default_templates']) {
                MailTemplateBase.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/MailTemplate>} module_templates
 */
MailTemplatesWithDefaults.prototype['module_templates'] = undefined;

/**
 * @member {Array.<module:model/MailTemplateBase>} default_templates
 */
MailTemplatesWithDefaults.prototype['default_templates'] = undefined;






export default MailTemplatesWithDefaults;

