/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MailTemplateType.
* @enum {}
* @readonly
*/
export default class MailTemplateType {
    
        /**
         * value: "report_created_admin"
         * @const
         */
        "report_created_admin" = "report_created_admin";

    
        /**
         * value: "report_created_user"
         * @const
         */
        "report_created_user" = "report_created_user";

    
        /**
         * value: "report_resolved_user"
         * @const
         */
        "report_resolved_user" = "report_resolved_user";

    

    /**
    * Returns a <code>MailTemplateType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MailTemplateType} The enum <code>MailTemplateType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

