/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModuleStats model module.
 * @module model/ModuleStats
 * @version 1.0.0
 */
class ModuleStats {
    /**
     * Constructs a new <code>ModuleStats</code>.
     * Represents statistics for a module.
     * @alias module:model/ModuleStats
     * @param moduleId {String} 
     */
    constructor(moduleId) { 
        
        ModuleStats.initialize(this, moduleId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, moduleId) { 
        obj['module_id'] = moduleId;
        obj['total_reports'] = 0;
        obj['total_files'] = 0;
        obj['total_reporters'] = 0;
        obj['total_actions'] = 0;
        obj['total_types'] = 0;
        obj['total_open_reports'] = 0;
    }

    /**
     * Constructs a <code>ModuleStats</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModuleStats} obj Optional instance to populate.
     * @return {module:model/ModuleStats} The populated <code>ModuleStats</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModuleStats();

            if (data.hasOwnProperty('module_id')) {
                obj['module_id'] = ApiClient.convertToType(data['module_id'], 'String');
            }
            if (data.hasOwnProperty('total_reports')) {
                obj['total_reports'] = ApiClient.convertToType(data['total_reports'], 'Number');
            }
            if (data.hasOwnProperty('total_files')) {
                obj['total_files'] = ApiClient.convertToType(data['total_files'], 'Number');
            }
            if (data.hasOwnProperty('total_reporters')) {
                obj['total_reporters'] = ApiClient.convertToType(data['total_reporters'], 'Number');
            }
            if (data.hasOwnProperty('total_actions')) {
                obj['total_actions'] = ApiClient.convertToType(data['total_actions'], 'Number');
            }
            if (data.hasOwnProperty('total_types')) {
                obj['total_types'] = ApiClient.convertToType(data['total_types'], 'Number');
            }
            if (data.hasOwnProperty('total_open_reports')) {
                obj['total_open_reports'] = ApiClient.convertToType(data['total_open_reports'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModuleStats</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModuleStats</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ModuleStats.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['module_id'] && !(typeof data['module_id'] === 'string' || data['module_id'] instanceof String)) {
            throw new Error("Expected the field `module_id` to be a primitive type in the JSON string but got " + data['module_id']);
        }

        return true;
    }


}

ModuleStats.RequiredProperties = ["module_id"];

/**
 * @member {String} module_id
 */
ModuleStats.prototype['module_id'] = undefined;

/**
 * @member {Number} total_reports
 * @default 0
 */
ModuleStats.prototype['total_reports'] = 0;

/**
 * @member {Number} total_files
 * @default 0
 */
ModuleStats.prototype['total_files'] = 0;

/**
 * @member {Number} total_reporters
 * @default 0
 */
ModuleStats.prototype['total_reporters'] = 0;

/**
 * @member {Number} total_actions
 * @default 0
 */
ModuleStats.prototype['total_actions'] = 0;

/**
 * @member {Number} total_types
 * @default 0
 */
ModuleStats.prototype['total_types'] = 0;

/**
 * @member {Number} total_open_reports
 * @default 0
 */
ModuleStats.prototype['total_open_reports'] = 0;






export default ModuleStats;

