/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrgWithMembershipState from './OrgWithMembershipState';

/**
 * The OrganizationGroupings model module.
 * @module model/OrganizationGroupings
 * @version 1.0.0
 */
class OrganizationGroupings {
    /**
     * Constructs a new <code>OrganizationGroupings</code>.
     * A class to group your organizations by their membership states.
     * @alias module:model/OrganizationGroupings
     */
    constructor() { 
        
        OrganizationGroupings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrganizationGroupings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrganizationGroupings} obj Optional instance to populate.
     * @return {module:model/OrganizationGroupings} The populated <code>OrganizationGroupings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganizationGroupings();

            if (data.hasOwnProperty('invites')) {
                obj['invites'] = ApiClient.convertToType(data['invites'], [OrgWithMembershipState]);
            }
            if (data.hasOwnProperty('reviewers')) {
                obj['reviewers'] = ApiClient.convertToType(data['reviewers'], [OrgWithMembershipState]);
            }
            if (data.hasOwnProperty('members')) {
                obj['members'] = ApiClient.convertToType(data['members'], [OrgWithMembershipState]);
            }
            if (data.hasOwnProperty('admins')) {
                obj['admins'] = ApiClient.convertToType(data['admins'], [OrgWithMembershipState]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrganizationGroupings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrganizationGroupings</code>.
     */
    static validateJSON(data) {
        if (data['invites']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['invites'])) {
                throw new Error("Expected the field `invites` to be an array in the JSON data but got " + data['invites']);
            }
            // validate the optional field `invites` (array)
            for (const item of data['invites']) {
                OrgWithMembershipState.validateJSON(item);
            };
        }
        if (data['reviewers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['reviewers'])) {
                throw new Error("Expected the field `reviewers` to be an array in the JSON data but got " + data['reviewers']);
            }
            // validate the optional field `reviewers` (array)
            for (const item of data['reviewers']) {
                OrgWithMembershipState.validateJSON(item);
            };
        }
        if (data['members']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['members'])) {
                throw new Error("Expected the field `members` to be an array in the JSON data but got " + data['members']);
            }
            // validate the optional field `members` (array)
            for (const item of data['members']) {
                OrgWithMembershipState.validateJSON(item);
            };
        }
        if (data['admins']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['admins'])) {
                throw new Error("Expected the field `admins` to be an array in the JSON data but got " + data['admins']);
            }
            // validate the optional field `admins` (array)
            for (const item of data['admins']) {
                OrgWithMembershipState.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/OrgWithMembershipState>} invites
 */
OrganizationGroupings.prototype['invites'] = undefined;

/**
 * @member {Array.<module:model/OrgWithMembershipState>} reviewers
 */
OrganizationGroupings.prototype['reviewers'] = undefined;

/**
 * @member {Array.<module:model/OrgWithMembershipState>} members
 */
OrganizationGroupings.prototype['members'] = undefined;

/**
 * @member {Array.<module:model/OrgWithMembershipState>} admins
 */
OrganizationGroupings.prototype['admins'] = undefined;






export default OrganizationGroupings;

