/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserOrganizationMembershipState from './UserOrganizationMembershipState';

/**
 * The OrgWithMembershipState model module.
 * @module model/OrgWithMembershipState
 * @version 1.0.0
 */
class OrgWithMembershipState {
    /**
     * Constructs a new <code>OrgWithMembershipState</code>.
     * A class to represent an organization with its membership state.
     * @alias module:model/OrgWithMembershipState
     * @param name {String} 
     * @param membershipState {module:model/UserOrganizationMembershipState} 
     */
    constructor(name, membershipState) { 
        
        OrgWithMembershipState.initialize(this, name, membershipState);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, membershipState) { 
        obj['name'] = name;
        obj['membership_state'] = membershipState;
    }

    /**
     * Constructs a <code>OrgWithMembershipState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrgWithMembershipState} obj Optional instance to populate.
     * @return {module:model/OrgWithMembershipState} The populated <code>OrgWithMembershipState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrgWithMembershipState();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('logo_url')) {
                obj['logo_url'] = ApiClient.convertToType(data['logo_url'], 'String');
            }
            if (data.hasOwnProperty('enabled_ai_list')) {
                obj['enabled_ai_list'] = ApiClient.convertToType(data['enabled_ai_list'], ['String']);
            }
            if (data.hasOwnProperty('enabled_ai')) {
                obj['enabled_ai'] = ApiClient.convertToType(data['enabled_ai'], 'Boolean');
            }
            if (data.hasOwnProperty('support_email')) {
                obj['support_email'] = ApiClient.convertToType(data['support_email'], 'String');
            }
            if (data.hasOwnProperty('membership_state')) {
                obj['membership_state'] = UserOrganizationMembershipState.constructFromObject(data['membership_state']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrgWithMembershipState</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrgWithMembershipState</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OrgWithMembershipState.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['logo_url'] && !(typeof data['logo_url'] === 'string' || data['logo_url'] instanceof String)) {
            throw new Error("Expected the field `logo_url` to be a primitive type in the JSON string but got " + data['logo_url']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['enabled_ai_list'])) {
            throw new Error("Expected the field `enabled_ai_list` to be an array in the JSON data but got " + data['enabled_ai_list']);
        }
        // ensure the json data is a string
        if (data['support_email'] && !(typeof data['support_email'] === 'string' || data['support_email'] instanceof String)) {
            throw new Error("Expected the field `support_email` to be a primitive type in the JSON string but got " + data['support_email']);
        }

        return true;
    }


}

OrgWithMembershipState.RequiredProperties = ["name", "membership_state"];

/**
 * @member {String} id
 */
OrgWithMembershipState.prototype['id'] = undefined;

/**
 * @member {String} name
 */
OrgWithMembershipState.prototype['name'] = undefined;

/**
 * @member {String} description
 */
OrgWithMembershipState.prototype['description'] = undefined;

/**
 * @member {String} logo_url
 */
OrgWithMembershipState.prototype['logo_url'] = undefined;

/**
 * @member {Array.<String>} enabled_ai_list
 */
OrgWithMembershipState.prototype['enabled_ai_list'] = undefined;

/**
 * @member {Boolean} enabled_ai
 */
OrgWithMembershipState.prototype['enabled_ai'] = undefined;

/**
 * @member {String} support_email
 */
OrgWithMembershipState.prototype['support_email'] = undefined;

/**
 * @member {module:model/UserOrganizationMembershipState} membership_state
 */
OrgWithMembershipState.prototype['membership_state'] = undefined;






export default OrgWithMembershipState;

