/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Type from './Type';

/**
 * The PaginatedResultType model module.
 * @module model/PaginatedResultType
 * @version 1.0.0
 */
class PaginatedResultType {
    /**
     * Constructs a new <code>PaginatedResultType</code>.
     * @alias module:model/PaginatedResultType
     * @param count {Number} Number of items available items in the database following given criteria
     * @param items {Array.<module:model/Type>} List of items returned in the response following given criteria
     */
    constructor(count, items) { 
        
        PaginatedResultType.initialize(this, count, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, count, items) { 
        obj['count'] = count;
        obj['items'] = items;
    }

    /**
     * Constructs a <code>PaginatedResultType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaginatedResultType} obj Optional instance to populate.
     * @return {module:model/PaginatedResultType} The populated <code>PaginatedResultType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginatedResultType();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [Type]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaginatedResultType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaginatedResultType</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaginatedResultType.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                Type.validateJSON(item);
            };
        }

        return true;
    }


}

PaginatedResultType.RequiredProperties = ["count", "items"];

/**
 * Number of items available items in the database following given criteria
 * @member {Number} count
 */
PaginatedResultType.prototype['count'] = undefined;

/**
 * List of items returned in the response following given criteria
 * @member {Array.<module:model/Type>} items
 */
PaginatedResultType.prototype['items'] = undefined;






export default PaginatedResultType;

