/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PersonDB model module.
 * @module model/PersonDB
 * @version 1.0.0
 */
class PersonDB {
    /**
     * Constructs a new <code>PersonDB</code>.
     * Extends the Person model to include the database only fields that shall not be reported to the user.
     * @alias module:model/PersonDB
     * @param moduleId {String} 
     */
    constructor(moduleId) { 
        
        PersonDB.initialize(this, moduleId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, moduleId) { 
        obj['module_id'] = moduleId;
    }

    /**
     * Constructs a <code>PersonDB</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonDB} obj Optional instance to populate.
     * @return {module:model/PersonDB} The populated <code>PersonDB</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonDB();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('module_id')) {
                obj['module_id'] = ApiClient.convertToType(data['module_id'], 'String');
            }
            if (data.hasOwnProperty('unique_partner_id')) {
                obj['unique_partner_id'] = ApiClient.convertToType(data['unique_partner_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('extra_data')) {
                obj['extra_data'] = ApiClient.convertToType(data['extra_data'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonDB</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonDB</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PersonDB.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['module_id'] && !(typeof data['module_id'] === 'string' || data['module_id'] instanceof String)) {
            throw new Error("Expected the field `module_id` to be a primitive type in the JSON string but got " + data['module_id']);
        }
        // ensure the json data is a string
        if (data['unique_partner_id'] && !(typeof data['unique_partner_id'] === 'string' || data['unique_partner_id'] instanceof String)) {
            throw new Error("Expected the field `unique_partner_id` to be a primitive type in the JSON string but got " + data['unique_partner_id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }

        return true;
    }


}

PersonDB.RequiredProperties = ["module_id"];

/**
 * @member {String} id
 */
PersonDB.prototype['id'] = undefined;

/**
 * @member {String} module_id
 */
PersonDB.prototype['module_id'] = undefined;

/**
 * @member {String} unique_partner_id
 */
PersonDB.prototype['unique_partner_id'] = undefined;

/**
 * @member {String} name
 */
PersonDB.prototype['name'] = undefined;

/**
 * @member {String} email
 */
PersonDB.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
PersonDB.prototype['phone'] = undefined;

/**
 * @member {Object.<String, Object>} extra_data
 */
PersonDB.prototype['extra_data'] = undefined;






export default PersonDB;

