/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ReportCategory.
* @enum {}
* @readonly
*/
export default class ReportCategory {
    
        /**
         * value: "hate_speech"
         * @const
         */
        "hate_speech" = "hate_speech";

    
        /**
         * value: "spam"
         * @const
         */
        "spam" = "spam";

    
        /**
         * value: "harassment"
         * @const
         */
        "harassment" = "harassment";

    
        /**
         * value: "pornography"
         * @const
         */
        "pornography" = "pornography";

    
        /**
         * value: "child_endangerment"
         * @const
         */
        "child_endangerment" = "child_endangerment";

    
        /**
         * value: "disinformation"
         * @const
         */
        "disinformation" = "disinformation";

    
        /**
         * value: "violence"
         * @const
         */
        "violence" = "violence";

    
        /**
         * value: "self_harm"
         * @const
         */
        "self_harm" = "self_harm";

    
        /**
         * value: "scam"
         * @const
         */
        "scam" = "scam";

    
        /**
         * value: "illegal_content"
         * @const
         */
        "illegal_content" = "illegal_content";

    
        /**
         * value: "other"
         * @const
         */
        "other" = "other";

    

    /**
    * Returns a <code>ReportCategory</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ReportCategory} The enum <code>ReportCategory</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

