/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ReportState.
* @enum {}
* @readonly
*/
export default class ReportState {
    
        /**
         * value: "pending"
         * @const
         */
        "pending" = "pending";

    
        /**
         * value: "ai_evaluating"
         * @const
         */
        "ai_evaluating" = "ai_evaluating";

    
        /**
         * value: "in_progress"
         * @const
         */
        "in_progress" = "in_progress";

    
        /**
         * value: "escalated"
         * @const
         */
        "escalated" = "escalated";

    
        /**
         * value: "rejected"
         * @const
         */
        "rejected" = "rejected";

    

    /**
    * Returns a <code>ReportState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ReportState} The enum <code>ReportState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

