/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReportState from './ReportState';

/**
 * The ReportDB model module.
 * @module model/ReportDB
 * @version 1.0.0
 */
class ReportDB {
    /**
     * Constructs a new <code>ReportDB</code>.
     * Extends the Report model to include the database only fields that shall not be reported to the user.
     * @alias module:model/ReportDB
     * @param moduleId {String} 
     * @param typeId {String} 
     * @param mainContentId {String} 
     */
    constructor(moduleId, typeId, mainContentId) { 
        
        ReportDB.initialize(this, moduleId, typeId, mainContentId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, moduleId, typeId, mainContentId) { 
        obj['module_id'] = moduleId;
        obj['type_id'] = typeId;
        obj['main_content_id'] = mainContentId;
    }

    /**
     * Constructs a <code>ReportDB</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportDB} obj Optional instance to populate.
     * @return {module:model/ReportDB} The populated <code>ReportDB</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportDB();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('module_id')) {
                obj['module_id'] = ApiClient.convertToType(data['module_id'], 'String');
            }
            if (data.hasOwnProperty('type_id')) {
                obj['type_id'] = ApiClient.convertToType(data['type_id'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('report_state')) {
                obj['report_state'] = ReportState.constructFromObject(data['report_state']);
            }
            if (data.hasOwnProperty('main_content_id')) {
                obj['main_content_id'] = ApiClient.convertToType(data['main_content_id'], 'String');
            }
            if (data.hasOwnProperty('reported_at')) {
                obj['reported_at'] = ApiClient.convertToType(data['reported_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReportDB</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReportDB</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ReportDB.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['module_id'] && !(typeof data['module_id'] === 'string' || data['module_id'] instanceof String)) {
            throw new Error("Expected the field `module_id` to be a primitive type in the JSON string but got " + data['module_id']);
        }
        // ensure the json data is a string
        if (data['type_id'] && !(typeof data['type_id'] === 'string' || data['type_id'] instanceof String)) {
            throw new Error("Expected the field `type_id` to be a primitive type in the JSON string but got " + data['type_id']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['main_content_id'] && !(typeof data['main_content_id'] === 'string' || data['main_content_id'] instanceof String)) {
            throw new Error("Expected the field `main_content_id` to be a primitive type in the JSON string but got " + data['main_content_id']);
        }
        // ensure the json data is a string
        if (data['secret'] && !(typeof data['secret'] === 'string' || data['secret'] instanceof String)) {
            throw new Error("Expected the field `secret` to be a primitive type in the JSON string but got " + data['secret']);
        }

        return true;
    }


}

ReportDB.RequiredProperties = ["module_id", "type_id", "main_content_id"];

/**
 * @member {String} description
 */
ReportDB.prototype['description'] = undefined;

/**
 * @member {String} module_id
 */
ReportDB.prototype['module_id'] = undefined;

/**
 * @member {String} type_id
 */
ReportDB.prototype['type_id'] = undefined;

/**
 * @member {String} id
 */
ReportDB.prototype['id'] = undefined;

/**
 * @member {module:model/ReportState} report_state
 */
ReportDB.prototype['report_state'] = undefined;

/**
 * @member {String} main_content_id
 */
ReportDB.prototype['main_content_id'] = undefined;

/**
 * @member {Date} reported_at
 */
ReportDB.prototype['reported_at'] = undefined;

/**
 * @member {Date} updated_at
 */
ReportDB.prototype['updated_at'] = undefined;

/**
 * @member {String} secret
 */
ReportDB.prototype['secret'] = undefined;






export default ReportDB;

