/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Type model module.
 * @module model/Type
 * @version 1.0.0
 */
class Type {
    /**
     * Constructs a new <code>Type</code>.
     * Model for Type. A type is a specific type of resource that can be used in a module.  E.g.: User, Chat-Room, Chat-Message, Forum-Post, etc.
     * @alias module:model/Type
     * @param name {String} 
     * @param moduleId {String} 
     */
    constructor(name, moduleId) { 
        
        Type.initialize(this, name, moduleId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, moduleId) { 
        obj['name'] = name;
        obj['module_id'] = moduleId;
        obj['is_user_type'] = false;
    }

    /**
     * Constructs a <code>Type</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Type} obj Optional instance to populate.
     * @return {module:model/Type} The populated <code>Type</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Type();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('module_id')) {
                obj['module_id'] = ApiClient.convertToType(data['module_id'], 'String');
            }
            if (data.hasOwnProperty('is_user_type')) {
                obj['is_user_type'] = ApiClient.convertToType(data['is_user_type'], 'Boolean');
            }
            if (data.hasOwnProperty('action_secret')) {
                obj['action_secret'] = ApiClient.convertToType(data['action_secret'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Type</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Type</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Type.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['module_id'] && !(typeof data['module_id'] === 'string' || data['module_id'] instanceof String)) {
            throw new Error("Expected the field `module_id` to be a primitive type in the JSON string but got " + data['module_id']);
        }
        // ensure the json data is a string
        if (data['action_secret'] && !(typeof data['action_secret'] === 'string' || data['action_secret'] instanceof String)) {
            throw new Error("Expected the field `action_secret` to be a primitive type in the JSON string but got " + data['action_secret']);
        }

        return true;
    }


}

Type.RequiredProperties = ["name", "module_id"];

/**
 * @member {String} id
 */
Type.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Type.prototype['name'] = undefined;

/**
 * @member {String} description
 */
Type.prototype['description'] = undefined;

/**
 * @member {String} module_id
 */
Type.prototype['module_id'] = undefined;

/**
 * @member {Boolean} is_user_type
 * @default false
 */
Type.prototype['is_user_type'] = false;

/**
 * @member {String} action_secret
 */
Type.prototype['action_secret'] = undefined;






export default Type;

