/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class UserOrganizationMembershipState.
* @enum {}
* @readonly
*/
export default class UserOrganizationMembershipState {
    
        /**
         * value: "invited"
         * @const
         */
        "invited" = "invited";

    
        /**
         * value: "reviewer"
         * @const
         */
        "reviewer" = "reviewer";

    
        /**
         * value: "member"
         * @const
         */
        "member" = "member";

    
        /**
         * value: "admin"
         * @const
         */
        "admin" = "admin";

    

    /**
    * Returns a <code>UserOrganizationMembershipState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/UserOrganizationMembershipState} The enum <code>UserOrganizationMembershipState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

