/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.ActionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ActionsApi', function() {
    describe('createAction', function() {
      it('should call createAction successfully', function(done) {
        //uncomment below and update the code to test createAction
        //instance.createAction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAction', function() {
      it('should call deleteAction successfully', function(done) {
        //uncomment below and update the code to test deleteAction
        //instance.deleteAction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionById', function() {
      it('should call getActionById successfully', function(done) {
        //uncomment below and update the code to test getActionById
        //instance.getActionById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllActionsOfType', function() {
      it('should call getAllActionsOfType successfully', function(done) {
        //uncomment below and update the code to test getAllActionsOfType
        //instance.getAllActionsOfType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserTypeActionById', function() {
      it('should call getUserTypeActionById successfully', function(done) {
        //uncomment below and update the code to test getUserTypeActionById
        //instance.getUserTypeActionById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('performAction', function() {
      it('should call performAction successfully', function(done) {
        //uncomment below and update the code to test performAction
        //instance.performAction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAction', function() {
      it('should call updateAction successfully', function(done) {
        //uncomment below and update the code to test updateAction
        //instance.updateAction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
