/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.AiApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AiApi', function() {
    describe('getAllAiModels', function() {
      it('should call getAllAiModels successfully', function(done) {
        //uncomment below and update the code to test getAllAiModels
        //instance.getAllAiModels(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllAiUsageForOrganization', function() {
      it('should call getAllAiUsageForOrganization successfully', function(done) {
        //uncomment below and update the code to test getAllAiUsageForOrganization
        //instance.getAllAiUsageForOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllMonthlyAiUsageForOrganization', function() {
      it('should call getAllMonthlyAiUsageForOrganization successfully', function(done) {
        //uncomment below and update the code to test getAllMonthlyAiUsageForOrganization
        //instance.getAllMonthlyAiUsageForOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMonthlyAiUsageForOrganizationModel', function() {
      it('should call getMonthlyAiUsageForOrganizationModel successfully', function(done) {
        //uncomment below and update the code to test getMonthlyAiUsageForOrganizationModel
        //instance.getMonthlyAiUsageForOrganizationModel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
