/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.MailTemplatesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MailTemplatesApi', function() {
    describe('createMailTemplate', function() {
      it('should call createMailTemplate successfully', function(done) {
        //uncomment below and update the code to test createMailTemplate
        //instance.createMailTemplate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMailTemplate', function() {
      it('should call deleteMailTemplate successfully', function(done) {
        //uncomment below and update the code to test deleteMailTemplate
        //instance.deleteMailTemplate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllMailTemplatesForModuleWithDefaults', function() {
      it('should call getAllMailTemplatesForModuleWithDefaults successfully', function(done) {
        //uncomment below and update the code to test getAllMailTemplatesForModuleWithDefaults
        //instance.getAllMailTemplatesForModuleWithDefaults(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMailTemplateById', function() {
      it('should call getMailTemplateById successfully', function(done) {
        //uncomment below and update the code to test getMailTemplateById
        //instance.getMailTemplateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMailTemplateByType', function() {
      it('should call getMailTemplateByType successfully', function(done) {
        //uncomment below and update the code to test getMailTemplateByType
        //instance.getMailTemplateByType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMailTemplatesForModule', function() {
      it('should call getMailTemplatesForModule successfully', function(done) {
        //uncomment below and update the code to test getMailTemplatesForModule
        //instance.getMailTemplatesForModule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMailTemplate', function() {
      it('should call updateMailTemplate successfully', function(done) {
        //uncomment below and update the code to test updateMailTemplate
        //instance.updateMailTemplate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
