/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.OrganizationsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrganizationsApi', function() {
    describe('acceptInvitationToOrganization', function() {
      it('should call acceptInvitationToOrganization successfully', function(done) {
        //uncomment below and update the code to test acceptInvitationToOrganization
        //instance.acceptInvitationToOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('changeMembershipState', function() {
      it('should call changeMembershipState successfully', function(done) {
        //uncomment below and update the code to test changeMembershipState
        //instance.changeMembershipState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createOrganization', function() {
      it('should call createOrganization successfully', function(done) {
        //uncomment below and update the code to test createOrganization
        //instance.createOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOrganization', function() {
      it('should call deleteOrganization successfully', function(done) {
        //uncomment below and update the code to test deleteOrganization
        //instance.deleteOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('denyInvitationToOrganization', function() {
      it('should call denyInvitationToOrganization successfully', function(done) {
        //uncomment below and update the code to test denyInvitationToOrganization
        //instance.denyInvitationToOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembershipState', function() {
      it('should call getMembershipState successfully', function(done) {
        //uncomment below and update the code to test getMembershipState
        //instance.getMembershipState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMyOrganizations', function() {
      it('should call getMyOrganizations successfully', function(done) {
        //uncomment below and update the code to test getMyOrganizations
        //instance.getMyOrganizations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMyOrganizationsGrouped', function() {
      it('should call getMyOrganizationsGrouped successfully', function(done) {
        //uncomment below and update the code to test getMyOrganizationsGrouped
        //instance.getMyOrganizationsGrouped(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganization', function() {
      it('should call getOrganization successfully', function(done) {
        //uncomment below and update the code to test getOrganization
        //instance.getOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationMembers', function() {
      it('should call getOrganizationMembers successfully', function(done) {
        //uncomment below and update the code to test getOrganizationMembers
        //instance.getOrganizationMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('inviteUserToOrganization', function() {
      it('should call inviteUserToOrganization successfully', function(done) {
        //uncomment below and update the code to test inviteUserToOrganization
        //instance.inviteUserToOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('inviteUserToOrganizationByEmail', function() {
      it('should call inviteUserToOrganizationByEmail successfully', function(done) {
        //uncomment below and update the code to test inviteUserToOrganizationByEmail
        //instance.inviteUserToOrganizationByEmail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leaveOrganization', function() {
      it('should call leaveOrganization successfully', function(done) {
        //uncomment below and update the code to test leaveOrganization
        //instance.leaveOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('revokeUserFromOrganization', function() {
      it('should call revokeUserFromOrganization successfully', function(done) {
        //uncomment below and update the code to test revokeUserFromOrganization
        //instance.revokeUserFromOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateOrganization', function() {
      it('should call updateOrganization successfully', function(done) {
        //uncomment below and update the code to test updateOrganization
        //instance.updateOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
