/**
 * UGC Guard API
 * API for UGC Guard. A tool to help you manage reports on user generated content.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UgcGuardJavascriptApi);
  }
}(this, function(expect, UgcGuardJavascriptApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UgcGuardJavascriptApi.ReportsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReportsApi', function() {
    describe('createMagicReport', function() {
      it('should call createMagicReport successfully', function(done) {
        //uncomment below and update the code to test createMagicReport
        //instance.createMagicReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createReport', function() {
      it('should call createReport successfully', function(done) {
        //uncomment below and update the code to test createReport
        //instance.createReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('escalateReport', function() {
      it('should call escalateReport successfully', function(done) {
        //uncomment below and update the code to test escalateReport
        //instance.escalateReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllReports', function() {
      it('should call getAllReports successfully', function(done) {
        //uncomment below and update the code to test getAllReports
        //instance.getAllReports(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContentOfReport', function() {
      it('should call getContentOfReport successfully', function(done) {
        //uncomment below and update the code to test getContentOfReport
        //instance.getContentOfReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnrichedEvaluationsOfReport', function() {
      it('should call getEnrichedEvaluationsOfReport successfully', function(done) {
        //uncomment below and update the code to test getEnrichedEvaluationsOfReport
        //instance.getEnrichedEvaluationsOfReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEvaluationsOfReport', function() {
      it('should call getEvaluationsOfReport successfully', function(done) {
        //uncomment below and update the code to test getEvaluationsOfReport
        //instance.getEvaluationsOfReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMyReports', function() {
      it('should call getMyReports successfully', function(done) {
        //uncomment below and update the code to test getMyReports
        //instance.getMyReports(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReportById', function() {
      it('should call getReportById successfully', function(done) {
        //uncomment below and update the code to test getReportById
        //instance.getReportById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReportersOfReport', function() {
      it('should call getReportersOfReport successfully', function(done) {
        //uncomment below and update the code to test getReportersOfReport
        //instance.getReportersOfReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rejectReport', function() {
      it('should call rejectReport successfully', function(done) {
        //uncomment below and update the code to test rejectReport
        //instance.rejectReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateReport', function() {
      it('should call updateReport successfully', function(done) {
        //uncomment below and update the code to test updateReport
        //instance.updateReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('validateReport', function() {
      it('should call validateReport successfully', function(done) {
        //uncomment below and update the code to test validateReport
        //instance.validateReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
